---
title: "SVR vs OLS Factor Return Prediction"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# --- 1. Setup ---
if(!require(tidyverse)){install.packages("tidyverse")}
if(!require(lubridate)){install.packages("lubridate")}
if(!require(e1071)){install.packages("e1071")}

library(tidyverse)
library(lubridate)
library(e1071)

run_svr <- TRUE
```

```{r}
# --- 2. Load Fama-French Data ---
temp <- tempfile()
url <- "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_CSV.zip"
download.file(url, temp, quiet = TRUE)

raw_ff <- read_csv(unz(temp, "F-F_Research_Data_Factors.csv"), skip = 3)

ff_data <- raw_ff %>%
  rename(date_raw = 1) %>%
  filter(nchar(as.character(date_raw)) == 6) %>%
  mutate(
    date = floor_date(ymd(paste0(date_raw, "01")), "month"),
    Mkt_RF = as.numeric(`Mkt-RF`) / 100,
    SMB    = as.numeric(SMB) / 100,
    HML    = as.numeric(HML) / 100
  ) %>%
  select(date, Mkt_RF, SMB, HML)
```

```{r}
# --- 3. Load Data ---
load("data_ml.RData")

data_ml <- data_ml %>%
  mutate(date = floor_date(as.Date(date), "month")) %>%
  filter(date > "1999-12-31", date < "2019-01-01") %>%
  left_join(ff_data, by = "date") %>%
  arrange(stock_id, date)
```

```{r}
# --- 4. Features ---
memory_features <- c("Mom_11M_Usd")
accounting_features <- c("Div_Yld", "Ebit_Bv")
market_features <- c("Mkt_Cap_6M_Usd", "Pb", "Vol1Y_Usd")
ff_features <- c("Mkt_RF", "SMB", "HML")

features <- c(memory_features, accounting_features, market_features, ff_features)

formula_ols <- as.formula(paste("R1M_Usd ~", paste(features, collapse = " + ")))
```

------------------------------------------------------------------------

## SVR Function (with Lightweight Tuning)

```{r}
run_svr_model_fixed <- function(train_data, test_data, features) {
  
  # Split 5-year train_data into: 4 years training, 1 year validation
  val_split_date <- max(train_data$date) %m-% months(12)
  
  sub_train <- train_data %>% filter(date <= val_split_date)
  sub_val   <- train_data %>% filter(date > val_split_date)
  
  # Prepare Matrices
  prep_data <- function(df) {
    x <- as.matrix(df[, features])
    x[is.na(x)] <- 0
    return(x)
  }
  
  x_sub_train <- prep_data(sub_train)
  x_sub_val   <- prep_data(sub_val)
  x_test      <- prep_data(test_data)
  
  # Scale based ONLY on sub_train to prevent leakage within the window
  x_sub_train_scaled <- scale(x_sub_train)
  center_val <- attr(x_sub_train_scaled, "scaled:center")
  scale_val  <- attr(x_sub_train_scaled, "scaled:scale")
  
  x_sub_val_scaled <- scale(x_sub_val, center = center_val, scale = scale_val)
  x_test_scaled    <- scale(x_test, center = center_val, scale = scale_val)
  
  # --- TUNING ON VALIDATION SET ---
  cost_grid  <- c(0.1, 1, 10)
  gamma_grid <- c(0.01, 0.05)
  
  best_mse <- Inf
  best_params <- list(cost = 1, gamma = 0.05)
  
  for (c_val in cost_grid) {
    for (g_val in gamma_grid) {
      fit <- svm(x = x_sub_train_scaled, y = sub_train$R1M_Usd,
                 type = "eps-regression", kernel = "radial",
                 cost = c_val, gamma = g_val)
      
      # Predict on validation set (NOT training set)
      val_preds <- predict(fit, x_sub_val_scaled)
      mse <- mean((sub_val$R1M_Usd - val_preds)^2)
      
      if (mse < best_mse) {
        best_mse <- mse
        best_params <- list(cost = c_val, gamma = g_val)
      }
    }
  }
  
  # Re-train on full 5-year window using best params
  x_train_full <- prep_data(train_data)
  x_train_full_scaled <- scale(x_train_full)
  
  final_fit <- svm(x = x_train_full_scaled, y = train_data$R1M_Usd,
                   type = "eps-regression", kernel = "radial",
                   cost = best_params$cost, gamma = best_params$gamma)
  
  # Scale test set using full training window parameters
  x_test_final_scaled <- scale(x_test, 
                               center = attr(x_train_full_scaled, "scaled:center"), 
                               scale = attr(x_train_full_scaled, "scaled:scale"))
  
  preds <- predict(final_fit, x_test_final_scaled)
  return(as.numeric(preds))
}
```

------------------------------------------------------------------------

## Rolling Window

```{r}
data_stock <- data_ml
window_length_years <- 5
months_in_window <- window_length_years * 12

all_dates <- sort(unique(data_stock$date))
test_dates <- all_dates[(months_in_window + 1):length(all_dates)]

results_list <- list()

for (i in 1:length(test_dates)) {
  current_date <- test_dates[i]
  
  train_data <- data_stock %>% filter(date < current_date) %>% tail(months_in_window)
  test_data  <- data_stock %>% filter(date == current_date)
  
  if(nrow(test_data) == 0 || nrow(train_data) < months_in_window) next
  
  # --- OLS ---
  fit_ols <- lm(formula_ols, data = train_data)
  pred_ols <- predict(fit_ols, test_data)
  
  # --- SVR ---
  if (run_svr) {
    pred_svr <- run_svr_model(train_data, test_data, features)
  } else {
    pred_svr <- rep(NA, nrow(test_data))
  }
  
  results_list[[i]] <- data.frame(
    date = current_date,
    actual = test_data$R1M_Usd,
    pred_ols = as.numeric(pred_ols),
    pred_svr = as.numeric(pred_svr)
  )
}

predictions_df <- bind_rows(results_list)
```

------------------------------------------------------------------------

## Evaluation Functions

```{r}
compute_mse <- function(y_true, y_pred) {
  mean((y_true - y_pred)^2)
}

compute_hit_ratio <- function(y_true, y_pred) {
  mean(sign(y_pred) == sign(y_true))
}

compute_oos_r2 <- function(y_true, y_pred) {
  1 - sum((y_true - y_pred)^2) / sum(y_true^2)
}

compute_ic <- function(y_true, y_pred) {
  c(
    pearson  = cor(y_true, y_pred),
    spearman = cor(y_true, y_pred, method = "spearman")
  )
}
```

------------------------------------------------------------------------

## Results

```{r}
cat("--- Performance Summary ---\n")

mse_ols <- compute_mse(predictions_df$actual, predictions_df$pred_ols)
mse_svr <- compute_mse(predictions_df$actual, predictions_df$pred_svr)

hit_ols <- compute_hit_ratio(predictions_df$actual, predictions_df$pred_ols)
hit_svr <- compute_hit_ratio(predictions_df$actual, predictions_df$pred_svr)

r2_ols <- compute_oos_r2(predictions_df$actual, predictions_df$pred_ols)
r2_svr <- compute_oos_r2(predictions_df$actual, predictions_df$pred_svr)

ic_ols <- compute_ic(predictions_df$actual, predictions_df$pred_ols)
ic_svr <- compute_ic(predictions_df$actual, predictions_df$pred_svr)

cat("MSE (OLS):", round(mse_ols, 6), "\n")
cat("MSE (SVR):", round(mse_svr, 6), "\n\n")

cat("Hit Ratio (OLS):", round(hit_ols, 4), "\n")
cat("Hit Ratio (SVR):", round(hit_svr, 4), "\n\n")

cat("OOS R² (OLS):", round(r2_ols, 4), "\n")
cat("OOS R² (SVR):", round(r2_svr, 4), "\n\n")

cat("IC (OLS):", round(ic_ols["spearman"], 4), "\n")
cat("IC (SVR):", round(ic_svr["spearman"], 4), "\n")
```

```{r}
plot(predictions_df$date, predictions_df$actual,
     type = "l", lty = 1,
     xlab = "Date", ylab = "Returns",
     main = "Actual vs SVR Predictions")

lines(predictions_df$date, predictions_df$pred_svr, lty = 2)
legend("topright", legend = c("Actual", "SVR"),
       lty = c(1,2))
```

```{r}
residuals <- predictions_df$actual - predictions_df$pred_svr

plot(predictions_df$pred_svr, residuals,
     xlab = "Predicted",
     ylab = "Residuals",
     main = "SVR Residual Plot",
     pch = 16)

abline(h = 0)
```

```{r}
strategy_returns <- sign(predictions_df$pred_svr) * predictions_df$actual

cum_actual <- cumsum(predictions_df$actual)
cum_strategy <- cumsum(strategy_returns)

plot(predictions_df$date, cum_actual,
     type = "l",
     xlab = "Date",
     ylab = "Cumulative Return",
     main = "SVR Strategy vs Market")

lines(predictions_df$date, cum_strategy, lty = 2)
legend("topleft", legend = c("Market", "SVR Strategy"),
       lty = c(1,2))
```
